
obj-y += $(KERNEL_DIR)/assert.o
obj-y += $(KERNEL_DIR)/config.o
#obj-y += $(KERNEL_DIR)/init_system.o
obj-y += $(KERNEL_DIR)/interrupt.o
obj-y += $(KERNEL_DIR)/main.o
obj-y += $(KERNEL_DIR)/syscall.o
obj-y += $(KERNEL_DIR)/machine.o
