
obj-y += $(NET_INET_DIR)/ip.o
obj-y += $(NET_INET_DIR)/arp.o
obj-y += $(NET_INET_DIR)/eth.o
obj-y += $(NET_INET_DIR)/tcp.o
obj-y += $(NET_INET_DIR)/udp.o
obj-y += $(NET_INET_DIR)/inet.o
obj-y += $(NET_INET_DIR)/icmp.o
obj-y += $(NET_INET_DIR)/inet_socket.o
